template = "https://github.com/giellalt/template-lang-und"
rev_id = 293
template_sha = "d22e247baeffac26e2fcc89a2b69592e66f6d04d"

[replacements]
__GLOTTOLOG_ID__ = "latv1249"
__REPO__ = "lang-lav"
__UND2C__ = "lv"
__UNDEFINED__ = "Latvian"
__UND__ = "lav"
