template = "https://github.com/giellalt/template-lang-und"
rev_id = 294
template_sha = "a620868b33dee503846060f7bd6c6e88f3c1f6d1"

[replacements]
__GLOTTOLOG_ID__ = "latv1249"
__REPO__ = "lang-lav"
__UND2C__ = "lv"
__UNDEFINED__ = "Latvian"
__UND__ = "lav"
