template = "https://github.com/giellalt/template-lang-und"
rev_id = 319
template_sha = "eda7c8f2efa7f16917002a5cc15e57ab9ecf2d1a"

[replacements]
__GLOTTOLOG_ID__ = "latv1249"
__REPO__ = "lang-lav"
__UND2C__ = "lv"
__UNDEFINED__ = "Latvian"
__UND__ = "lav"
